### PR TITLE
🐛 Fix cant play some youtube link

### PR DESCRIPTION
**Pull request by nitpum**
From #24 bot can't play some youtube video
And from https://github.com/Androz2091/discord-player/issues/848 
we can fix it by passing some ytdlOptions

### CODE REVIEW

**Comment by krgainer** [comment]
Hmm, I can only maintain stability with the bot when highWaterMark is at 1<<30, as opposed to 25. Other than that, though, this fix is working great.

I made a fork for this change specifically, but if you'd rather update your fork/pull request, I can delete mine :)

**Comment by nitpum** [comment]
@krgainer I'm not sure about 30, as many people test with 25 (From https://github.com/Androz2091/discord-player/issues/848 and [MusicBot](https://github.com/ZerioDev/Music-bot/blob/master/config.js) ) and it works perfectly.

If 30 work for the most people I will update this, for now I will remain `1 << 25`

**Comment by nitpum** [comment]
@krgainer Updated `1 << 30` :)

**Comment by krgainer** [comment]
> @krgainer Updated `1 << 30` :)

Thanks so much! The stability issues I was having were occurring while hosting the bot on both AWS and GCP (free tiers), though locally didn't seem to have any issues. Thanks for the fix, I'll recend my pull request now!

**Review by Androz2091 — APPROVED** [review]

**Pull request merged**
