### PR TITLE
:sparkles: Added /history command

### PR DESCRIPTION
**Pull request by CanadaBry**
Simple history command to display previous songs.

### CODE REVIEW

**Comment by CanadaBry** [comment]
I haven't made many PRs before,  so accidentally have some "leftover" commits. only real commit is 0fb1af1. Just a fun command I wrote, won't be offended if you don't want it in your branch :)

**Comment by Androz2091** [comment]
Thank you for your contribution! 👍

Can you start the bot so it generates a new readme with the new command?

**Comment by CanadaBry** [comment]
Sorry about that, I almost always run it in docker, so forgot it didn't update the README

**Comment by Androz2091** [comment]
All right, no problem. One little small thing, can you use an uppercase character for Display instead of display to stay consistent with the other commands?
You can update the command in the js file then run the bot - readme will be updated.

**Review by Androz2091 — APPROVED** [review]
I will do it, do not worry. Thank you for your contribution! 👍

**Comment by CanadaBry** [comment]
Oh thanks! Sorry I’ve been busy and wouldn’t have been able to make changes till Monday.

**Pull request merged**
